[package]
name = "walls"
version = "0.1.0"
authors = ["L <rohesie@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.6"
yaml-rust = "0.4.4"
png = "0.16.7"
deflate = "0.8.6"
