#The path of the file to open.
file_to_open: "./colors.png"

#Name for the file to output and the icon-state prefixes.
#Example output with "wall" as input: "wall.png" -> wall-0-0-0-0, wall-0-0-0-1, wall-0-0-1-0...
output_name: "colors"

#Tiles are 32x32 squares, so the possible coordinates here range from (0,0) in the top-left corner to (32,32) in the bottom-right one.
#Of course, both of those extremes, plus things beyond them, are invalid options.
#Top-down sprites are centered in the middle (16,16).
#The same is not true in the Y axis for 3/4 walls in general, with the center being elevated by the perspective.
center_x: 16
center_y: 6

#If enabled, it will produce a file for every possible corner variant (20 in total).
#Useful for debugging purposes.
produce_corners: false

#These coordinates are in tile-sized steps.
#The top-left tile is in coordinates (0,0).
#The maximum valid x value is ((pixel-width / 32) - 1), substitute for height for y.
#This means that a hypothetical rectangle with 3x2 sprites, 3 in the x-axis and 2 in the y, will range from coordinates (0,0) to (2,1).
se_convex_x: 3
se_convex_y: 3
nw_convex_x: 3
nw_convex_y: 3
ne_convex_x: 3
ne_convex_y: 3
sw_convex_x: 3
sw_convex_y: 3

se_concave_x: 1
se_concave_y: 1
nw_concave_x: 1
nw_concave_y: 1
ne_concave_x: 1
ne_concave_y: 1
sw_concave_x: 1
sw_concave_y: 1

se_horizontal_x: 1
se_horizontal_y: 3
nw_horizontal_x: 1
nw_horizontal_y: 3
ne_horizontal_x: 1
ne_horizontal_y: 3
sw_horizontal_x: 1
sw_horizontal_y: 3

se_vertical_x: 3
se_vertical_y: 1
nw_vertical_x: 3
nw_vertical_y: 1
ne_vertical_x: 3
ne_vertical_y: 1
sw_vertical_x: 3
sw_vertical_y: 1

se_flat_x: 5
se_flat_y: 1
nw_flat_x: 5
nw_flat_y: 1
ne_flat_x: 5
ne_flat_y: 1
sw_flat_x: 5
sw_flat_y: 1
